config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  match '/products/search',to: 'products#search', via: :get, :as => 'search_path'
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  root :to => redirect('/products')
  resources :users

  match '/about', to: 'products#about', via: :get, :as => 'about_path'
  match '/products/:id/transaction', to: 'products#transaction', via: :get, :as => 'transaction_path'

  # User Logins/History
  match '/login',  to: 'sessions#new', via: :get, :as => 'login_path'
  match '/logout', to: 'sessions#destroy', via: :delete, :as => 'logout_path'
  get '/auth/:provider/callback', to: 'sessions#create'
  match '/history/purchase', to: 'users#purchase', via: :get, :as => 'purchase_history_path'
  match '/history/seller', to: 'users#seller', via: :get, :as => 'seller_history_path'

  # Shopping Cart
  match '/products/add_shopping_cart', to: 'products#add_shopping_cart', via: :post, :as => 'shopping_cart'
  match '/shopping_cart/index', to: 'shopping_cart#index', via: :get, :as => 'view_shopping_cart'
  match '/shopping_cart/checkout', to: 'shopping_cart#checkout', via: :post, :as => 'checkout'
  match '/shopping_cart/checkout/confirm_purchase', to: 'shopping_cart#confirm_purchase', via: :post, :as => 'confirm_purchase'
  match '/shopping_cart/destroy_all', to: 'shopping_cart#destroy_all', via: :delete, as: 'destroy_all_shopping_cart'

  # Bookmarks
  match '/products/:id/bookmark', to: 'products#bookmark_from_product', via: :get, :as => 'bookmark_from_product'
  match '/products/add_bookmarks', to: 'products#add_bookmarks', via: :post, :as => 'bookmark'
  match '/bookmarks/index', to: 'bookmarks#index', via: :get, :as => 'view_bookmarks'
  match '/bookmarks/delete', to:'bookmarks#destroy', via: :post, :as => 'delete_all_bookmarks'
  match '/bookmarks/:id/delete_one', to:'bookmarks#delete_one', via: :post, :as => "delete_one_bookmark"
  #match '/bookmarks/delete_one', to:'bookmarks#delete_one', via: :post, :as => "no_bookmark"

  # Seller Reviews
  match '/review', to: 'products#new_seller_review', via: :get, :as => 'new_seller_review'
  match '/review/new', to: 'products#add_review', via: :post, :as => 'add_review'

  resources :shopping_cart
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :product
  has_one :wallet

  # User implementation should be credited to the slides titled Slides11.ppx presented in class
  # and "Single Sign-On and Third Party Authentication"
  # presented in class during week of 11/6

  ## Additional documentation
  # Additional tutorial for implementation: https://dev.to/anne46/google-omniauth-in-a-rails-app-36ka
  # Additional implentation strategies: https://github.com/zquestz/omniauth-google-oauth2

  before_save {|user| user.email=user.email.downcase}
  before_save :create_session_token

  private
  def create_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth['uid']
      user.provider = auth['provider']
      user.email = auth['info']['email']
      user.name = auth['info']['name']
      user.pfp = auth['info']['image']
      # default is set to 0: we can change this for testing
      user.build_wallet(wallet: 0.0)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # User implementation should be credited to the slides titled "Single Sign-On and Third Party Authentication"
  # presented in class during week of 11/6

  ## Additional documentation
  # Additional tutorial for implementation: https://dev.to/anne46/google-omniauth-in-a-rails-app-36ka
  # Additional implentation strategies: https://github.com/zquestz/omniauth-google-oauth2

  before_action :set_current_user
  before_action :set_current_shopping_cart

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address,:password,:password_confirmation)
  end

  def show
    @wallet = Wallet.where(user_id: @current_user.id).first
    @seller_reviews = SellerReview.where(user_id: @current_user.id)
    id = params[:id]
    unless current_user?(id)
      flash[:warning] = "Can only show profile of logged-in user"
    end
  end

  def index
    # render 'index' template
  end

  def new
    # default: render 'new' template
  end

  def create
    # left empty
  end

  def edit
    # render 'edit'
  end

  def update
    # update product
  end

  def destroy
    # destroy user
  end

  def purchase
    @user_purchases = Purchase.where(user_id: @current_user.id)
  end
end

app/views/users/purchase.html.haml
%p.spacing
%h1.title_text.center Your Purchases

.product_listing
  %table.product_listing_display
    - if @user_purchases.empty?
      %tr
        %th.title_text You have no recorded purchases
    - else
      - @user_purchases.order(purchase_timestamp: :desc).each do |item|
        %tr.product_listing_row
          %td.border_radius_left
            .listing_img
              = link_to image_tag(item.product.image.url, :height => "400", :class => "card-img"), product_path(item.product.id)
            .product_alignment_fields
              %p.listing-text= "Name: " + item.product.name
              %p.listing-text= "Category: " + item.product.category
              %p.listing-text= 'Listing Price: $' + item.product.price.to_s
              %p.listing-text= Purchase.where(:product_id => item.product.id).first.purchase_timestamp
          %td.border_radius_right
            .product_listing.right
              %p= link_to "More Info", product_path(item.product.id), class: "bookmark_button"
              %p= link_to "Add Review", new_seller_review_path(review_id: item.product.user_id), class: "bookmark_button"

.profile_button
  = link_to 'Return to Profile', "/users/#{@current_user[:id]}"


%p.spacing

app/views/users/seller.html.haml
%p.spacing
%h1.title_text.center Items up for sale

%h2.title_text.center Sold Items

.product_listing
  %table.product_listing_display
    - Product.where(:user_id => @current_user.id, :is_sold => true).each do |product|
      %tr.product_listing_row
        %td.border_radius_left
          .listing_img
            = link_to image_tag(product.image.url, :height => "400", :class => "card-img"), product_path(product.id)
          .product_alignment_fields
            %p.listing-text= "Name: " + product.name
            %p.listing-text= "Category: " + product.category
            %p.listing-text= 'Money Made: $' + product.transaction
            %p.listing-text= Purchase.where(:product_id => product.id).first.purchase_timestamp
        %td.border_radius_right
          .product_listing.right
            %p= link_to "More Info", product_path(product.id), class: "bookmark_button"


  %h2.title_text.center Items Not Sold Yet

.product_listing
  %table.product_listing_display
    - Product.where(:user_id => @current_user.id, :is_sold => false).each do |product|
      %tr.product_listing_row
        %td.border_radius_left
          .listing_img
            = link_to image_tag(product.image.url, :height => "400", :class => "card-img"), product_path(product.id)
          .product_alignment_fields
            %p.listing-text= "Name: " + product.name
            %p.listing-text= "Category: " + product.category
            %p.listing-text= 'Listing Price: $' + product.price.to_s
            %p.listing-text= 'Up for sale.'

        %td.border_radius_right
          .product_listing.right
            %p= link_to "More Info", product_path(product.id), class: "bookmark_button"

.profile_button
  = link_to 'Return to Profile', "/users/#{@current_user[:id]}"

%p.spacing

app/views/users/show.html.haml
.profile_button
  %h2.title_text #{@current_user.name}'s Account
  %h4.title_text Email
  %p.title_text #{@current_user.email}
  %h4.title_text In-store credit
  %p.title_text $#{'%.2f' % @wallet.wallet}

.profile_button
  = link_to 'Add a New Product to Sell?', new_product_path

.profile_button
  = link_to 'View Purchase History', purchase_history_path_url

.profile_button
  = link_to 'View Seller History', seller_history_path_url
%p

- if !@seller_reviews.nil?
  .review_card_display
    %h4.header_text Your Reviews:
    %table.review_table
      - @seller_reviews.each do |r|
        %tr.review_row
          %td.review_column
            %p.review_text=((('&starf;'.html_safe) + ' ')  * r.rating)
            %p.review_text= '&ldquo;'.html_safe + r.review + '&rdquo;'.html_safe
          %td.review_stars
            %p.review_name= "Reviewer: " + r.name

%p.spacing