config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  match '/products/search',to: 'products#search', via: :get, :as => 'search_path'
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  root :to => redirect('/products')
  resources :users

  match '/about', to: 'products#about', via: :get, :as => 'about_path'
  match '/products/:id/transaction', to: 'products#transaction', via: :get, :as => 'transaction_path'

  # User Logins/History
  match '/login',  to: 'sessions#new', via: :get, :as => 'login_path'
  match '/logout', to: 'sessions#destroy', via: :delete, :as => 'logout_path'
  get '/auth/:provider/callback', to: 'sessions#create'
  match '/history/purchase', to: 'users#purchase', via: :get, :as => 'purchase_history_path'
  match '/history/seller', to: 'users#seller', via: :get, :as => 'seller_history_path'

  # Shopping Cart
  match '/products/add_shopping_cart', to: 'products#add_shopping_cart', via: :post, :as => 'shopping_cart'
  match '/shopping_cart/index', to: 'shopping_cart#index', via: :get, :as => 'view_shopping_cart'
  match '/shopping_cart/checkout', to: 'shopping_cart#checkout', via: :post, :as => 'checkout'
  match '/shopping_cart/checkout/confirm_purchase', to: 'shopping_cart#confirm_purchase', via: :post, :as => 'confirm_purchase'
  match '/shopping_cart/destroy_all', to: 'shopping_cart#destroy_all', via: :delete, as: 'destroy_all_shopping_cart'

  # Bookmarks
  match '/products/:id/bookmark', to: 'products#bookmark_from_product', via: :get, :as => 'bookmark_from_product'
  match '/products/add_bookmarks', to: 'products#add_bookmarks', via: :post, :as => 'bookmark'
  match '/bookmarks/index', to: 'bookmarks#index', via: :get, :as => 'view_bookmarks'
  match '/bookmarks/delete', to:'bookmarks#destroy', via: :post, :as => 'delete_all_bookmarks'
  match '/bookmarks/:id/delete_one', to:'bookmarks#delete_one', via: :post, :as => "delete_one_bookmark"
  #match '/bookmarks/delete_one', to:'bookmarks#delete_one', via: :post, :as => "no_bookmark"

  # Seller Reviews
  match '/review', to: 'products#new_seller_review', via: :get, :as => 'new_seller_review'
  match '/review/new', to: 'products#add_review', via: :post, :as => 'add_review'

  resources :shopping_cart
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  def self.compute_total_price(shopping_cart_list, current_wallet, use_wallet)
    total_price = 0
    shopping_cart_list.each do |item|
      total_price += item.product.price.to_f
    end
    total_price = sprintf("%.2f", total_price)
    if use_wallet
      if current_wallet > total_price.to_f
        total_price = 0
      else
        total_price = total_price.to_f - current_wallet
      end
    end
    sprintf("%.2f", total_price)
  end

  def self.update_wallet(current_wallet, total_price)
    if current_wallet.wallet > total_price
      current_wallet.wallet = current_wallet.wallet - total_price
    else
      current_wallet.wallet = 0
    end
    current_wallet.save
  end

  def self.buy_each_shopping_cart_item(item, current_user)
    item.product.set_sold_true
    Purchase.create!(user_id: current_user.id, product_id: item.product.id, purchase_timestamp: Time.now)
    price = item.product.price.to_f
    user_selling = User.where(id: item.product.user_id).first
    user_wallet = Wallet.find_by_user_id(user_selling.id)
    user_wallet.update(wallet: user_wallet.wallet + item.product.transaction.to_f)
    ShoppingCart.destroy(item.id)
    price
  end
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController

  before_action :set_current_user
  before_action :set_current_shopping_cart


  def shopping_cart_params
    params.permit(:id, :use_wallet_balance, :user_id, :product_id,address: [:city,:state,:zip,:street_address], credit_card: [:credit_card_name,:credit_card_number,:credit_card_security_num,:credit_card_expiration])
  end

  def index
    ShoppingCart.where(user_id: @current_user.id).each do |item|
      if item.product.is_sold.eql? true

          flash[:notice] = "#{item.product.name} was sold."
          ShoppingCart.destroy(item)
      end
    end
    @current_shopping_cart_list = ShoppingCart.where(user_id: @current_user.id)
    @wallet = Wallet.where(user_id: @current_user.id).first
  end

  def edit
    # add later
  end

  def checkout
    @current_shopping_cart_list = ShoppingCart.where(user_id: @current_user.id)
    current_wallet = Wallet.find_by_user_id(@current_user.id).wallet
    use_wallet = shopping_cart_params[:use_wallet_balance] == 'on'
    @total_price = ShoppingCart::compute_total_price(@current_shopping_cart_list, current_wallet, use_wallet)
  end

  def confirm_purchase
    @current_shopping_cart_list = ShoppingCart.where(user_id: @current_user.id)
    current_wallet = Wallet.find_by_user_id(@current_user.id).wallet
    use_wallet = shopping_cart_params[:use_wallet_balance] == 'on'
    @total_price = ShoppingCart::compute_total_price(@current_shopping_cart_list, current_wallet, use_wallet)

    if !shopping_cart_params[:address][:city].empty? && !shopping_cart_params[:address][:state].empty? &&!shopping_cart_params[:address][:street_address].empty? &&!shopping_cart_params[:address][:zip].empty?
      @lookup = Purchase.valid_address(shopping_cart_params[:address][:city],shopping_cart_params[:address][:state],shopping_cart_params[:address][:street_address],shopping_cart_params[:address][:zip])
      if @total_price.to_f > 0.00
        @valid_card = Wallet.check_credit(shopping_cart_params[:credit_card][:credit_card_name],shopping_cart_params[:credit_card][:credit_card_number],shopping_cart_params[:credit_card][:credit_card_security_num],shopping_cart_params[:credit_card][:credit_card_expiration])
      else
        @valid_card = ''
      end

      if @lookup.is_a?(Hash) && @valid_card == ''
        current_wallet = Wallet.find_by_user_id(@current_user.id)
        total_price = 0
        @current_shopping_cart_list = ShoppingCart.where(user_id: @current_user.id)
        @current_shopping_cart_list.each do |item|
          total_price += ShoppingCart::buy_each_shopping_cart_item(item, @current_user)
        end

        if shopping_cart_params[:use_wallet_balance] == 'on'
          ShoppingCart::update_wallet(current_wallet, total_price)
        end

        flash[:notice] = "Purchased successfully!"
        redirect_to products_path
      elsif @lookup.is_a?(String)
        flash[:notice] = 'Error' + @lookup
        render checkout_path
      elsif @valid_card != ''
        flash[:notice] = @valid_card
        render checkout_path
      else
        flash[:notice] = 'Not a valid address'
        render checkout_path
      end
    else
      flash[:notice] = 'Please fill in every address box'
      render checkout_path
    end

  end

  def destroy_all
    ShoppingCart.where(user_id: @current_user.id).destroy_all
    flash[:notice] = "Shopping Cart Cleared!"
    redirect_to view_shopping_cart_path
  end
end

app/views/shopping_cart/checkout.html.haml
= form_tag confirm_purchase_path do
    %h2.title_text.center Shipping Address
    .edit_product_form
        %table.table_center
            %tr
                %td.edit_body
                    = label :address, :street_address, 'Street Address', class: "product_subtext"
                %td.edit_field_body
                    = text_field :address, 'street_address', class: "generic_fields"
            %tr
                %td.edit_body
                    = label :address, :state, 'State', class: "product_subtext"
                %td.edit_field_body
                    = text_field :address, 'state', class: "generic_fields"
            %tr
                %td.edit_body
                    = label :address, :city, 'City', class: "product_subtext"
                %td.edit_field_body
                    = text_field :address, 'city', class: "generic_fields"
            %tr
                %td.edit_body
                    = label :address, :zip, 'Zip', class: "product_subtext"
                %td.edit_field_body
                    = text_field :address, 'zip', class: "generic_fields"

    - if @total_price.to_f > 0.00
        %h2.title_text.center Credit Card Information
    .edit_product_form
        - if @total_price.to_f > 0.00
            %table.table_center
                %tr
                    %td.edit_body
                        = label :credit_card, :credit_card_name, 'Name', class: "product_subtext"
                    %td.edit_field_body
                        = text_field :credit_card, 'credit_card_name', class: "generic_fields"
                %tr
                    %td.edit_body
                        = label :credit_card, :credit_card_number, 'Credit Card Number', class: "product_subtext"
                    %td.edit_field_body
                        = text_field :credit_card, 'credit_card_number', class: "generic_fields"
                %tr
                    %td.edit_body
                        = label :credit_card, :credit_card_security_num, 'CVV', class: "product_subtext"
                    %td.edit_field_body
                        = text_field :credit_card, 'credit_card_security_num', class: "generic_fields"
                %tr
                    %td.edit_body
                        = label :credit_card, :credit_card_expiration, 'Expiration Date', class: "product_subtext"
                    %td.edit_field_body
                        = text_field :credit_card, 'credit_card_expiration', class: "generic_fields"

        %h4.title_text Total Price: $#{@total_price}

        %p.title_text Buy Product?
        = hidden_field_tag :use_wallet_balance, params[:use_wallet_balance]
        = submit_tag 'Purchase', :id => 'confirm_purchase_button', class: "general_button"

%p.spacing

app/views/shopping_cart/index.html.haml
%table#shopping_cart_top_buttons
  %tr
    %td.shopping-cart-home-button
      = link_to "Return Home", products_path, class: "clear-cart-button"
    %td.shopping-cart-clear-button
      = button_to 'Clear Shopping Cart', destroy_all_shopping_cart_path, method: :delete, data: { confirm: 'Are you sure you want to clear your shopping cart?' }, class: "clear-cart-button"

%h2.title_text.center Shopping Cart

= form_tag checkout_path, :id => 'user_shopping_cart' do
  - if @current_shopping_cart_list.nil? || @current_shopping_cart_list.empty?
    %h4.title_text.center You have no items in your shopping cart
    %h4.title_text.center Wallet Balance: $#{'%.2f' % @wallet.wallet}
  - else
    - total_price = 0
    .product_listing
      %table.product_listing_display
        - @current_shopping_cart_list.each do |item|
          %tr.product_listing_row
            %td.border_radius_left
              .listing_img
                = link_to image_tag(item.product.image.url, :height => "400", :class => "card-img"), product_path(item.product.id)
              .product_alignment_fields
                %p.listing-text= "Name: " + item.product.name
                %p.listing-text= "Category: " + item.product.category
                %p.listing-text= 'Listing Price: $' + item.product.price.to_s
            %td.border_radius_right
              .product_listing.right
                %p= link_to "More Info", product_path(item.product.id), class: "bookmark_button"
            - total_price += item.product.price.to_f

      %h6.title_text Total Price: $#{'%.2f' % total_price}

      %h6.title_text
        = check_box_tag :use_wallet_balance, nil, false, id: 'use_wallet_balance', class: 'styled-checkbox'
        = label_tag 'use_wallet_balance', 'Use Wallet Balance ($' + '%.2f' % @wallet.wallet + ')?', class: 'styled-label'

      = submit_tag 'Check Out', :id => 'check_out_button', class: "clear-cart-button"
%p.spacing