config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check
  match '/products/search',to: 'products#search', via: :get, :as => 'search_path'
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  root :to => redirect('/products')
  resources :users

  match '/about', to: 'products#about', via: :get, :as => 'about_path'
  match '/products/:id/transaction', to: 'products#transaction', via: :get, :as => 'transaction_path'

  # User Logins/History
  match '/login',  to: 'sessions#new', via: :get, :as => 'login_path'
  match '/logout', to: 'sessions#destroy', via: :delete, :as => 'logout_path'
  get '/auth/:provider/callback', to: 'sessions#create'
  match '/history/purchase', to: 'users#purchase', via: :get, :as => 'purchase_history_path'
  match '/history/seller', to: 'users#seller', via: :get, :as => 'seller_history_path'

  # Shopping Cart
  match '/products/add_shopping_cart', to: 'products#add_shopping_cart', via: :post, :as => 'shopping_cart'
  match '/shopping_cart/index', to: 'shopping_cart#index', via: :get, :as => 'view_shopping_cart'
  match '/shopping_cart/checkout', to: 'shopping_cart#checkout', via: :post, :as => 'checkout'
  match '/shopping_cart/checkout/confirm_purchase', to: 'shopping_cart#confirm_purchase', via: :post, :as => 'confirm_purchase'
  match '/shopping_cart/destroy_all', to: 'shopping_cart#destroy_all', via: :delete, as: 'destroy_all_shopping_cart'

  # Bookmarks
  match '/products/:id/bookmark', to: 'products#bookmark_from_product', via: :get, :as => 'bookmark_from_product'
  match '/products/add_bookmarks', to: 'products#add_bookmarks', via: :post, :as => 'bookmark'
  match '/bookmarks/index', to: 'bookmarks#index', via: :get, :as => 'view_bookmarks'
  match '/bookmarks/delete', to:'bookmarks#destroy', via: :post, :as => 'delete_all_bookmarks'
  match '/bookmarks/:id/delete_one', to:'bookmarks#delete_one', via: :post, :as => "delete_one_bookmark"
  #match '/bookmarks/delete_one', to:'bookmarks#delete_one', via: :post, :as => "no_bookmark"

  # Seller Reviews
  match '/review', to: 'products#new_seller_review', via: :get, :as => 'new_seller_review'
  match '/review/new', to: 'products#add_review', via: :post, :as => 'add_review'

  resources :shopping_cart
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb

class Product < ActiveRecord::Base

  mount_uploader :image, ImageUploader

  belongs_to :user

  validates :name, presence: true, length: {maximum: 50}
  validates :category, presence: true, length: {maximum: 50}
  validates :quality, presence: true
  validates :description, presence: true, length: {maximum: 100}
  VALID_PRICE_REGEX = /\d+()|(.\d\d)/
  validates :price, presence: true, format: {with: VALID_PRICE_REGEX} # Regex for US dollar format
  validates :street_address, presence: true
  validates :state, presence: true
  validates :city, presence: true
  validates :zip, presence: true

  def transaction
    price = self.price.to_i
    if price < 10
      commission_price = price - (0.1 * price)
    else
      commission_price = price - (0.15 * price)
    end
    commission_to_return = "%.2f" % [commission_price]
  end
  def valid_price?
    price_regex = /\A\d+\.\d{2}\z/
    self.price.match?(price_regex)
  end

  def valid_quality?
    ['Well Worn', 'Used', 'Like New', 'New'].include?(self.quality)
  end

  def valid_category?
    ['Home', 'Entertainment', 'Clothing', 'Personal Care', 'Office', 'Other'].include?(self.category)
  end

  def self.valid_address(city,state,address,zip)
    run_it = true
    if run_it
      client = SmartyStreetsConfig.client
      lookup = SmartyStreets::USStreet::Lookup.new
      lookup.street = address
      lookup.state = state
      lookup.city = city
      lookup.zipcode = zip
      lookup.candidates = 1
      lookup.match = SmartyStreets::USStreet::MatchType::STRICT
      begin
        client.send_lookup(lookup)
      rescue SmartyStreets::SmartyError => err
        result = "Got the error" + err.to_s
        return result
      end
      result = lookup.result
      if result.empty?
        false
      else
        lat = result[0].metadata.latitude
        long = result[0].metadata.longitude
        maps_hash = {:lat => lat, :long => long}
        return maps_hash
      end
    else
      maps_hash = {:lat => 0.0, :long => 0.0}
      return maps_hash
    end
  end

  def self.filtered_search(search,category,quality)
    products = Product.all
    products = products.where('name LIKE ?', "%#{search}%") if search.present?
    products = products.where(quality: quality) if quality.present? && quality != 'None'
    products = products.where(category: category) if category.present? && category != 'None'

    products
  end

  def self.add_to_shopping_cart(user_id, product_id)
    var = ShoppingCart.where(user_id: user_id).where(product_id: product_id).present?
    unless var.present?
      shopping_cart_item = { :user_id => user_id, :product_id => product_id }
      ShoppingCart.create!(shopping_cart_item)
    end
  end

  def self.add_to_bookmarks(user_id, product_id)
    var = Bookmark.where(user_id: user_id).where(product_id: product_id).present?
    unless var.present?
      bookmark = { :user_id => user_id, :product_id => product_id }
      Bookmark.create!(bookmark)
    end
  end

  def set_sold_true
    self.is_sold = true
    self.save
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_current_user
  before_action :set_current_shopping_cart

  def product_params
    params.require(:product).permit(:name,:image,:category,:quality,:description,:price,:street_address,:state,:city,:zip,:is_sold,:seller_review,:review_id, :lat, :long)
  end
  def show
    id = params[:id]
    @current_product = Product.find_by_id(id)
    @current_product.increment!(:product_traffic)
    @seller_reviews = SellerReview.where(user_id: @current_product.user_id)
  end

  def index
    @products = Product.where(is_sold: false).where.not(user_id: @current_user.id).order("product_traffic desc")
    if !@products.empty? && !@products.nil?
      @priority_products = @products.select{|product| product.image?}
      if @priority_products.length > 5
        @priority_products = @priority_products.take(5)
      end
    end
    sorting
  end

  def search
    search_query = params[:search].presence || ''
    category = params[:product] ? params[:product][:categories].presence || 'None' : 'None'
    quality = params[:product] ? params[:product][:quality].presence || 'None' : 'None'
    @products = Product.filtered_search(search_query, category, quality).where(is_sold: false).order("product_traffic desc")
    if @products.empty?
      flash[:notice] = "No products match your search, try another search"
      @products = Product.filtered_search(search_query, 'None', 'None').where(is_sold: false).order("product_traffic desc")
    end
    sorting
  end

  def new
  end

  def create
    product_parameters = product_params.to_h
    product_parameters[:user_id] = @current_user.id
    @lookup = check_address
    if @lookup.is_a?(Hash)
      product_parameters = product_parameters.merge(@lookup)
      @product = Product.create(product_parameters)
      # @product.user_id = @current_user.id
      if @product.save
        flash[:notice] = "Product created successfully!"
        redirect_to products_path
      else
        errors = @product.errors.full_messages
        puts "Validation failed with errors: #{errors.join(', ')}"
        render 'new'
      end
    elsif @lookup.is_a?(String)
      flash[:notice]= "Error " + @lookup
      render 'new'
    else
      flash[:notice]= "Address validation failed error"
      render 'new'
    end

  end

  def edit
    id = params[:id]
    product = Product.find_by_id(id)
    if @current_user.id.eql?(product.user_id)
      @current_product = product
    else
      flash[:notice] = "This is not a product you are selling"
      redirect_to product_path(id)
    end
  end

  def update
    id = params[:id]
    @product = Product.find_by_id(id)
    @product.update(product_params)
    flash[:notice] = "Product was updated successfully."
    redirect_to products_path
  end

  def destroy
    # destroy product
    @current_product = Product.find_by_id(params[:id])
    @current_product.destroy!
  end

  def about
    # edit later
  end

  def transaction
    @current_product = Product.find_by_id(params[:id])
    Product::add_to_shopping_cart(@current_user.id, @current_product.id)
    flash[:notice] = "#{@current_product.name} was added to your shopping cart."
    redirect_to products_path
  end

  def add_shopping_cart
    if params[:products] != nil
      params[:products].keys.each do |id|
        Product::add_to_shopping_cart(@current_user.id, id)
      end
      flash[:notice] = "Product(s) were successfully added to your shopping cart."
    else
      flash[:warning] = "No products were selected"
    end
    redirect_to products_path
  end

  def sorting
    if params[:sort] && params[:direction]
      @products = Product.where(is_sold: false).where.not(user_id: @current_user.id)
      sort_direction = params[:direction] == 'asc' ? 'desc' : 'asc'
      case params[:sort]
      when 'product_name'
        @products = @products.order("name #{sort_direction}")
      when 'price'
        @products = @products.order(Arel.sql("CAST(price AS float) #{sort_direction}"))
      else
        @products = @products.order("#{params[:sort]} #{sort_direction}")
      end
    end
    if params[:search]
      @products = @products.where('name LIKE ?', "%#{params[:search]}%")
    end
    if params[:product] && params[:product][:categories].present? && params[:product][:categories] != 'None'
      @products = @products.where(category: params[:product][:categories])
    end
    if params[:product] && params[:product][:quality].present? && params[:product][:quality] != 'None'
      @products = @products.where(quality: params[:product][:quality])
    end
    @products = @products.where(is_sold: false).where.not(user_id: @current_user.id)
  end

  def add_bookmarks
    if params[:products] != nil
      params[:products].keys.each do |id|
        Product::add_to_bookmarks(@current_user.id, id)
      end
      flash[:notice] = "Product(s) were successfully added to bookmarks."
    else
      flash[:warning] = "No products were selected"
    end
    redirect_to products_path
  end

  def bookmark_from_product
    @current_product = Product.find_by_id(params[:id])
    Product::add_to_bookmarks(@current_user.id, @current_product.id)
    flash[:notice] = "#{@current_product.name} was added to your bookmarks."
    redirect_to products_path
  end

  def add_review
    if params[:seller_review] != nil
      SellerReview.create!(user_id: params[:review_id], name: @current_user.name, review: params[:seller_review][:review], rating: params[:seller_review][:rating])
      flash[:notice] = "Review successfully added"
      redirect_to purchase_history_path_path
    else
      flash[:notice] = "Missing required field"
      render new_seller_review_path
    end
  end

  def check_address
    if product_params[:city] != nil && product_params[:state] != nil && product_params[:street_address] != nil && product_params[:zip] != nil
      @lookup = Product.valid_address(product_params[:city],product_params[:state],product_params[:street_address],product_params[:zip])
      return @lookup
    else
      render new_product_path
    end

  end
  private
  def current_user
    @current_user
  end
end

app/views/products/about.html.haml
.product-index-form
  %h2.title_text FAQ
  %h4.title_text Where do I start?
  %p.about_divs Please first login using Google to interact with our services. Then you can see the display of currently available items for purchase! If you see a listing to your liking, you can select it and add it to your cart or you can add it to your bookmarks for later. There you'll checkout and adding shipping/payment information which will then be processed and your purchase will be complete.
  %h4.title_text How can I start selling?
  %p.about_divs On your individual profile page, you'll see a button that allows you to add a product to be sold on the website ('Add a Product to Sell?' link)
  %h4.title_text What can I do with an account?
  %p.about_divs With your account you can view your current user history as a buyer and seller. In seller history, you'll see all the items you have sold prior, or are currently selling. Here you can also select the item to view the item's information page and edit the item's page if need be. You can also view the items you have already purchased using our services.
  %h4.title_text How do I search for a product?
  %p.about_divs On the homepage, enter the item that you're looking for. Once you click search, it'll return products that match your search. You can also filter for specific categories or quality of items for a more specific search. Everytime a search is initiated, you'll see exact results or some results that may resemble your search terms. From the search results, you can also sort by name or price to help narrow your searches.

  .profile_button
    = link_to 'Return to Home', products_path

%p.spacing

app/views/products/edit.html.haml
%p.spacing
= link_to '&lt;'.html_safe, product_path(@current_product.id), class: "basic_link_button"

%h2.title_text.center Edit Product

= form_tag product_path(@current_product), :method => :put, multipart: true do
  .edit_product_form
    %table.table_center
      %tr
        %td.edit_body
          = label :product, :name, 'Product Name', class: "product_subtext"
        %td.edit_field_body
          = text_field :product, 'name', value: @current_product.name, class: "generic_fields"
      %tr
        %td.edit_body
          = label :product, :image, 'Product Image', class: "product_subtext"
        %td.edit_field_body
          = file_field :product, :image
      %tr
        %td.edit_body
          = label :product, :category, 'Product Category', class: "product_subtext"
        %td.edit_field_body
          = select :product, :category, options_for_select(['Home', 'Entertainment', 'Clothing', 'Personal Care', 'Office', 'Other'], @current_product.category)
      %tr
        %td.edit_body
          = label :product, :quality, 'Product Quality', class: "product_subtext"
        %td.edit_field_body
          = select :product, :quality, options_for_select(['New', 'Like New', 'Used', 'Well Worn'], @current_product.quality)
      %tr
        %td.edit_body
          = label :product, :description, 'Product Description', class: "product_subtext"
        %td.edit_field_body
          = text_area :product, :description, cols: "40", rows: "5", maxlength: "100", value: @current_product.description, class: "generic_fields"
      %tr
        %td.edit_body
          = label :product, :price, 'Price', class: "product_subtext"
          %p.product_subtext *include shipping price
        %td.edit_field_body
          = text_field :product, 'price', value: @current_product.price, class: "generic_fields"

    = submit_tag 'Confirm', class: "general_button"

%p.spacing

app/views/products/index.html.haml
%html
  %head
    %title Index Page
    = javascript_include_tag "index", "data-turbolinks-track" => true
    -# = javascript_include_tag 'application'
    -# = csrf_meta_tags

.welcome_statement
  =image_tag "icons/logo.png", :width => "300"

= form_tag search_path_path, :method => 'get', :class => "product-index-form" do
  .product_search_bar
    = text_field_tag :search, params[:search], placeholder: 'Search Products &#x26B2;'.html_safe, class: "product_search_field"

    .product_alignment_fields
      = label :product, :categories, "Category:", class: "background-text"
      = select :product, :quality, ['None','Well Worn', 'Used', 'Like New', 'New'], selected: params.dig(:product, :quality)
    .product_alignment_fields
      = label  :product, :quality, "Quality:", class: "background-text"
      = select :product, :categories, ['None', 'Home', 'Entertainment', 'Clothing', 'Personal Care', 'Office', 'Other'], selected: params.dig(:product, :categories)
    = submit_tag 'Search', :id => 'search_button', class: "search_button"

.product_card_display
  = link_to 'Sort by Name', products_path(sort: 'product_name', direction: toggle_direction('product_name'), search: params[:search], product: { categories: params.dig(:product, :categories), descriptions: params.dig(:product, :descriptions) }), class: "sort_button"
  = link_to 'Sort by Price', products_path(sort: 'price', direction: toggle_direction('price'), search: params[:search], product: { categories: params.dig(:product, :categories), descriptions: params.dig(:product, :descriptions) }), class: "sort_button"

%p.spacing
.product_card_display
  - @products.each do |product|
    .product_card
      = link_to image_tag(product.image.url, :height => "400", :class => "card-img"), product_path(product.id)
      %p.card-text= product.name
      %p.card-price= "$" + product.price
      %p.card-text= product.category
      %p.card-text= product.quality
      %p
      = link_to 'Add to shopping cart', transaction_path_url(product.id), class: "card-button"

      = link_to '&starf;'.html_safe, bookmark_from_product_path(product.id), class: "card-button"

-if !@priority_products.nil? && !@priority_products.empty?
  -count = 0
  %h4.title_text.center Our Popular Products!
  .carousel
    - @priority_products.each do |product|
      -count = count + 1
      =link_to (image_tag product.image.url, :height => "400", class: "carousel-slide fade"), product_path(product.id)
  .dots
    -count.times do
      %span.dot

%p.spacing

app/views/products/new.html.haml
%p.spacing
= link_to '&lt;'.html_safe, products_path,class: "basic_link_button"

%h2.title_text.center New Product

= form_tag products_path, :method => 'post', multipart: true do
  .edit_product_form
    %table.table_center
      %tr
        %td.edit_body
          = label :product, :name, 'Product Name', class: "product_subtext"
        %td.edit_field_body
          = text_field :product, 'name', class: "generic_fields"
      %tr
        %td.edit_body
          = label :product, :image, 'Product Image', class: "product_subtext"
        %td.edit_field_body
          = file_field :product, :image
      %tr
        %td.edit_body
          = label :product, :category, 'Product Category', class: "product_subtext"
        %td.edit_field_body
          = select :product, :category, ['Home', 'Entertainment', 'Clothing', 'Personal Care', 'Office', 'Other']
      %tr
        %td.edit_body
          = label :product, :quality, 'Product Quality', class: "product_subtext"
        %td.edit_field_body
          = select :product, :quality, ['New', 'Like New', 'Used', 'Well Worn']
      %tr
        %td.edit_body
          = label :product, :description, 'Product Description', class: "product_subtext"
        %td.edit_field_body
          = text_area :product, :description, cols: "40", rows: "5", maxlength: "100", class: "generic_fields"
      %tr
        %td.edit_body
          = label :product, :price, 'Price', class: "product_subtext"
          %p.product_subtext *include shipping price
        %td.edit_field_body
          = text_field :product, 'price', class: "generic_fields"
      %tr
        %td.edit_body
          = label :product, :street_address, 'Street Address', class: "product_subtext"
        %td.edit_field_body
          = text_field :product, 'street_address', class: "generic_fields"
      %tr
        %td.edit_body
          = label :product, :state, 'State', class: "product_subtext"
        %td.edit_field_body
          = text_field :product, 'state', class: "generic_fields"
      %tr
        %td.edit_body
          = label :product, :city, 'City', class: "product_subtext"
        %td.edit_field_body
          = text_field :product, 'city', class: "generic_fields"
      %tr
        %td.edit_body
          = label :product, :zip, 'Zip', class: "product_subtext"
        %td.edit_field_body
          = text_field :product, 'zip', class: "generic_fields"

    = submit_tag 'Confirm', class: "general_button"

%p.spacing

app/views/products/new_seller_review.html.haml
= form_tag add_review_path :method => 'post' do
  %h2.header_text Write a Review
  .edit_product_form
    %table.table_center
      %tr
        %td.edit_field_body
          = text_area :seller_review, :review, rows: 5, class: "generic_fields"
    %p
    = select :seller_review, :rating, [1, 2, 3, 4, 5]
    = hidden_field_tag :review_id, params[:review_id]
    = submit_tag 'Add Seller Review', :id => 'new_seller_review', class: "general_button"

app/views/products/search.html.haml
%html
  %head
    %title Search Page
    = javascript_include_tag "index"
    -# = javascript_include_tag 'application'
    -# = csrf_meta_tags

.welcome_statement
  %h4.title_text Search Results

= form_tag search_path_path, :method => 'get', :class => "product-search-form" do
  .product_search_bar
    = text_field_tag :search, params[:search], placeholder: 'Search Products &#x26B2;'.html_safe, class: "product_search_field"

    .product_alignment_fields
      = label :product, :categories, "Category:", class: "background-text"
      = select :product, :quality, ['None','Well Worn', 'Used', 'Like New', 'New'], selected: params.dig(:product, :quality)
    .product_alignment_fields
      = label  :product, :quality, "Description:", class: "background-text"
      = select :product, :categories, ['None', 'Home', 'Entertainment', 'Clothing', 'Personal Care', 'Office', 'Other'], selected: params.dig(:product, :categories)
    = submit_tag 'Search', :id => 'search_button', class: "search_button"

.product_card_display
  = link_to 'Sort by Name', products_path(sort: 'product_name', direction: toggle_direction('product_name'), search: params[:search], product: { categories: params.dig(:product, :categories), descriptions: params.dig(:product, :descriptions) }), class: "sort_button"
  = link_to 'Sort by Price', products_path(sort: 'price', direction: toggle_direction('price'), search: params[:search], product: { categories: params.dig(:product, :categories), descriptions: params.dig(:product, :descriptions) }), class: "sort_button"


%p.spacing
.product_card_display
  - @products.each do |product|
    .product_card
      = link_to image_tag(product.image.url, :height => "400", :class => "card-img"), product_path(product.id)
      %p.card-text= product.name
      %p.card-price= "$" + product.price
      %p.card-text= product.category
      %p.card-text= product.quality
      %p
      = link_to 'Add to shopping cart', transaction_path_url(product.id), class: "card-button"

      = link_to '&starf;'.html_safe, bookmark_from_product_path(product.id), class: "card-button"

app/views/products/show.html.haml
%html
  %head
    %title Index Page
    = javascript_include_tag "map"
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}&callback=initMap",
    defer: true

%p.spacing
= link_to 'Return to Home', products_path, class: "general_button"

.product_show_display
  %table.product_img_description
    %tr
      %td.product_row_body
        = image_tag @current_product.image.url, :width => "400", :class => "main-product-img"
      %td.product_row_body
        %h2.header_text #{@current_product.name}
        %p.product_text Category: #{@current_product.category}
        %p.product_text Quality: #{@current_product.quality}
        %p.product_text $#{@current_product.price}
        -if @current_product.is_sold == false
          -if @current_user.id.eql?(@current_product.user_id)
            = link_to 'Edit Item', edit_product_path(@current_product), class: "basic_link_button"
          -else
            = link_to 'Add to shopping cart', transaction_path_url, class: "basic_link_button"
            = link_to 'Bookmark', bookmark_from_product_path, class: "basic_link_button"
          %p.product_subtext #{@current_product.product_traffic} people have viewed this item

.product_description
  %h2.header_text Description
  %p #{@current_product.description}

.map-container
  %h2.header_text #{@current_product.name} Location:
  #product_map.product_map{ "data-latitude" => @current_product.lat.to_f, "data-longitude" => @current_product.long.to_f}
  %p#product_location{ "data-latitude" => @current_product.lat, "data-longitude" => @current_product.long, "data-name" => @current_product.name }

%p.spacing

- if !@seller_reviews.empty? && !@seller_reviews.nil?
  .review_card_display
    %h4.header_text Seller Reviews
    %table.review_table
      - @seller_reviews.each do |r|
        %tr.review_row
          %td.review_column
            %p.review_text=((('&starf;'.html_safe) + ' ')  * r.rating)
            %p.review_text= '&ldquo;'.html_safe + r.review + '&rdquo;'.html_safe
          %td.review_stars
            %p.review_name= "Reviewer: " + r.name


%p.spacing